Repository Merck/gsDesign2, pull requests merged in 2024-02, with the labels that each got.

#328 add error message checking the integer sample size
  R/gs_power_wlr.R
  R/to_integer.R
  tests/testthat/test-independent-fixed_design.R
  vignettes/articles/story-compare-power-delay-effect.Rmd
  vignettes/articles/story-summarize-designs.Rmd
Labels: enhancement

#329 289 vignette of the information under the null and alternative hypothesis
  _pkgdown.yml
  vignettes/articles/story-info-formula.Rmd
Labels: documentation

#333 Update `NEWS.md` for gsDesign2 1.1.1
  DESCRIPTION
  NEWS.md
Labels: CRAN

#336 Update vignette for spending bounds under nph
  .lintr
  vignettes/articles/story-design-with-spending.Rmd
  vignettes/articles/usage-gs-spending-bound.Rmd
Labels: documentation

#342 re-org vignettes and references
  .lintr
  R/fixed_design_ahr.R
  R/fixed_design_fh.R
  R/fixed_design_lf.R
  R/fixed_design_maxcombo.R
  R/fixed_design_mb.R
  R/fixed_design_milestone.R
  R/fixed_design_rd.R
  R/fixed_design_rmst.R
  _pkgdown.yml
  man/fixed_design.Rd
  man/fixed_design_ahr.Rd
  man/fixed_design_fh.Rd
  man/fixed_design_lf.Rd
  man/fixed_design_maxcombo.Rd
  man/fixed_design_mb.Rd
  man/fixed_design_milestone.Rd
  man/fixed_design_rd.Rd
  man/fixed_design_rmst.Rd
  vignettes/articles/story-seven-test-types.Rmd
Labels: documentation

#345 add `creat_arm` by lose `sum(accr_para) == 1` to `is_wholenumber(sum(accr_para) - 1)`
  R/utility_wlr.R
  man/gs_create_arm.Rd
Labels: bug

#351 Make `n` and `event` integers
  R/to_integer.R
Labels: bug
